import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import Home from "../../pages/page";

import { GoogleOAuthProvider } from '@react-oauth/google';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <GoogleOAuthProvider clientId="798476314558-f8vm69jaf32cvsclgtosvu2upc7i0v5k.apps.googleusercontent.com">
          <div className="m-auto overflow-hidden h-[100vh]">
            <Navbar />
            <main className="flex gap-6 md:gap-20">
              <div className="h-[92vh] mt-[10vh] overflow-hidden xl:hover:overflow-auto ">
                <Sidebar />
              </div>
              <div className="mt-4 flex flex-col gap-10 overflow-auto h-[99vh] videos flex-1 mt-[10vh]">
                {children}
              </div>
              {/* TikTik */}
            </main>
          </div>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
